### ISSUE TITLE
Decide what to do about the DTO interfaces

### ISSUE THREAD

**Issue by william-stacken** [Cactu5/recruitment-application#40]
This is not a high priority issue, but I would like to bring up the subject that the DTO interfaces have not seen much practical use. There is a lot of them, and I wonder if it's really neccessary to include an "AvailabliityDTO" interface, since which class other than "Availability" would implement it? Should it be standardized to use the DTOs, and if so, how? The repository classes does not use them, which makes it seem forced to use them anywhere else.

**Comment by william-stacken** [comment]
To illustrate what I mean, see https://github.com/Cactu5/recruitment-application/pull/37/files#diff-d14308feac678c23fa2898bef2d4f8672672f838bfc921517075ba3e525638fcR91.

This function takes a PersonDTO as an argument, but converts it to a "Person" regardless because the repository requires it.

**Comment by Cactu5** [comment]
We should discuss this during the meeting tomorrow.
